/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is normally auto-generated by `next dev` / `next build` and
// should not be edited by hand — checked in here only so `tsc --noEmit` has
// something to resolve against before the first `next` run generates it.
